const {test}=require('node:test');
const assert=require('node:assert/strict');
const api=require('./ops-sales-performance.js');
const fixture=require('../tests/fixtures/sales-performance-week.json');
const fresh=()=>JSON.parse(JSON.stringify(fixture));
test('empty store has one calm state, no fabricated figures',()=>{const h=api.renderHTML({rows:[]});assert.match(h,/No week published yet/);assert.doesNotMatch(h,/kpis|What is stuck/);});
test('example maps row-owned enquiries, proof-backed wins and unknown patio money',()=>{const d=fresh(),all=api.model(d),f=api.model(d,{lane:'fencing'}),p=api.model(d,{lane:'patio'});assert.equal(all.enquiries,25);assert.equal(f.enquiries,17);assert.equal(p.enquiries,8);assert.equal(f.winCount,3);assert.equal(f.winValue,11037.4);assert.equal(f.quotedJobs,18);assert.equal(all.winCount,3);assert.equal(all.quotedJobs,18);assert.equal(all.quotedValue,170907.55);assert.equal(all.winLane,'fencing');assert.equal(all.quotedLane,'fencing');assert.equal(p.quotedValue,null);assert.equal(p.winCount,null);assert.equal(all.elapsed,18.1);assert.equal(p.elapsed,27.83);assert.equal(all.actions.length,30);});
test('zero, null, gaps, nested gaps and missing lane remain distinct',()=>{const d=fresh(),r=d.rows[0];r.metrics.quoted_jobs=0;assert.equal(api.model(d,{lane:'fencing'}).quotedJobs,0);r.coverage.gaps.push('quoted_jobs','followup');assert.equal(api.model(d,{lane:'fencing'}).quotedJobs,null);assert.equal(api.read(r,'followup.count'),null);r.coverage.gaps.push('daily');assert.equal(api.model(d,{lane:'fencing'}).enquiries,null);d.rows.pop();assert.equal(api.model(d).actions,null);assert.match(api.renderHTML(d),/Patio has no report/);assert.doesNotMatch(api.renderHTML(d),/NaN|undefined/);});
test('source filter changes all attributable populations and withholds unsegmented values',()=>{const m=api.model(fresh(),{lane:'fencing',source:'Stratco'});assert.equal(m.enquiries,7);assert.equal(m.winCount,0);assert.equal(m.actions.length,7);assert.equal(m.quotedJobs,0);assert.equal(m.quotedValue,0);assert.equal(m.elapsed,null);assert.equal(m.scalar('stale'),null);});
test('customer names only resolve via contact id on authenticated read; escape all dynamic copy',()=>{const d=fresh(),a=d.rows[0].metrics.actions[0];a.name='Store name must never show';a.contact_id='synthetic-contact';a.suburb='Synthetic suburb';a.owed='<img src=x onerror=alert(1)>';let html=api.renderHTML(d);assert.match(html,/Synthetic suburb/);assert.doesNotMatch(html,/Store name must never show|<img/);assert.match(html,/&lt;img/);d.contacts_by_id={'synthetic-contact':{name:'Joined <name>'}};html=api.renderHTML(d);assert.match(html,/Joined &lt;name&gt;/);});
test('action groups include urgent cases in owner totals, age frozen to report week',()=>{const h=api.renderHTML(fresh());assert.match(h,/Promised 41 days ago/);assert.match(h,/Khairo<span>18 waiting/);assert.match(h,/Nithin<span>10 waiting/);assert.match(h,/Marnin<span>2 waiting/);assert.match(h,/up 9 on last week/);assert.doesNotMatch(h,/<details[^>]+open/);});
test('unpaid deposit or bare CRM won never supplies accepted weekly jobs',()=>{const d=fresh();d.rows[0].metrics.wins=[{job:'no-proof',value:999}];const m=api.model(d,{lane:'fencing'});assert.equal(m.winCount,null);assert.equal(m.winValue,null);delete d.rows[0].metrics.wins;assert.equal(api.model(d,{lane:'fencing'}).winCount,null);});
test('quotes sort by value and expansion is real; prior null never becomes a zero comparison',()=>{const d=fresh();d.rows[0].metrics.quote_rows.reverse();const h=api.renderHTML(d,{lane:'fencing'});assert.match(h,/Show all 18/);assert.ok(h.indexOf('SWF-261424')<h.indexOf('SWF-261273'));assert.match(h,/last week –/);const expanded=api.renderHTML(d,{lane:'fencing',showAllQuotes:true});assert.match(expanded,/Show fewer/);assert.match(expanded,/SWF-261434/);});
test('older weekly rows cannot leak into selected week',()=>{const d=fresh();d.rows.push({...d.rows[0],week_start:'2026-09-07',metrics:{quoted_jobs:99999}});assert.equal(api.model(d,{lane:'fencing'}).quotedJobs,18);});
test('authenticated reader makes one request, supports empty envelope and recoverable errors',async()=>{const calls=[];global.opsFetch=async(action,params)=>{calls.push({action,params});return {rows:[]};};await api.load('2026-09-14');assert.deepEqual(calls,[{action:'sales_performance_read',params:{week_start:'2026-09-14'}}]);assert.equal(api.state.error,null);global.opsFetch=async()=>{throw Error('Sign in required');};await api.load();assert.equal(api.state.error,'Sign in required');assert.equal(api.state.loading,false);});
test('late response never replaces more recently requested week',async()=>{let resolve;global.opsFetch=(_a,p)=>p.week_start==='2026-09-07'?new Promise(r=>resolve=r):Promise.resolve(fresh());const pending=api.load('2026-09-07');await api.load('2026-09-14');resolve({rows:[],week_start:'2026-09-07'});await pending;assert.equal(api.state.week,'2026-09-14');});

test('coverage gaps override derived source totals and preserve unrelated lane readings',()=>{const d=fresh(),r=d.rows[0];r.coverage.gaps.push('quoted_value');assert.equal(api.model(d,{lane:'fencing',source:'Phone'}).quotedValue,null);r.coverage.gaps=['patio_quote_total'];assert.equal(api.model(d,{lane:'fencing'}).quotedValue,170907.55);});

test('prior comparisons use flattened keys only',()=>{const d=fresh(),r=d.rows[0];r.metrics.prior={...JSON.parse(JSON.stringify(r.metrics)),quoted_jobs:12,won:9};const m=api.model(d,{lane:'fencing'});assert.equal(m.previous('quoted_jobs'),12);assert.equal(m.previous('won'),9);assert.equal(m.previous('enquiries'),null);assert.equal(m.previous('customers_waiting'),null);const html=api.renderHTML(d,{lane:'fencing'});assert.match(html,/down 6 on last week/);assert.match(html,/last week –/);});

test('All quotes and wins keep the measured lane when the other is a gap',()=>{const d=fresh();const html=api.renderHTML(d);assert.match(html,/Quotes sent \(fencing\)/);assert.match(html,/Quoted value \(fencing\)/);assert.match(html,/Won \(fencing\)/);const all=api.model(d);assert.equal(all.quotedJobs,18);assert.equal(all.winCount,3);const patio=d.rows[1];patio.coverage.gaps=patio.coverage.gaps.filter(g=>g!=='patio_quote_total'&&g!=='patio_wins');patio.metrics.quoted_jobs=4;patio.metrics.quoted_value=22000;patio.metrics.quote_rows=[{job:'SWP-1',value:22000,source:'Web'}];patio.metrics.wins=[{job:'SWP-1',value:22000,proof:'staff stamp',rep:'Nithin',source:'Web'}];const both=api.model(d);assert.equal(both.quotedJobs,22);assert.equal(both.quotedValue,192907.55);assert.equal(both.winCount,4);assert.equal(both.quotedLane,null);assert.equal(both.winLane,null);assert.doesNotMatch(api.renderHTML(d),/Quotes sent \(fencing\)|Won \(fencing\)/);d.rows[0].coverage.gaps.push('quoted_jobs','quoted_value','quote_rows','wins');const none=api.model(d);assert.equal(none.quotedJobs,4);assert.equal(none.winCount,1);assert.equal(none.quotedLane,'patio');assert.equal(none.winLane,'patio');assert.match(api.renderHTML(d),/Quotes sent \(patio\)/);assert.match(api.renderHTML(d),/Won \(patio\)/);d.rows[1].coverage.gaps.push('quoted_jobs','quoted_value','quote_rows','wins');const empty=api.model(d);assert.equal(empty.quotedJobs,null);assert.equal(empty.quotedValue,null);assert.equal(empty.winCount,null);assert.equal(empty.quotedLane,null);assert.equal(empty.winLane,null);const patioOnly=api.model(fresh(),{lane:'patio'});assert.equal(patioOnly.quotedJobs,null);assert.equal(patioOnly.winCount,null);assert.doesNotMatch(api.renderHTML(fresh(),{lane:'patio'}),/Quotes sent \(patio\)|Won \(patio\)/);});

test('All story extras, last-week priors and missing-row notice follow the measured lane',()=>{
  const published=fresh();
  const all=api.model(published);
  assert.equal(all.winLane,'fencing');
  assert.equal(all.scalar('lost_week',all.winLane),5);
  assert.equal(all.scalar('tracked.accepted',all.winLane),0);
  assert.equal(all.scalar('tracked.count',all.winLane),12);
  assert.equal(all.scalar('lost_week'),null);
  const publishedHtml=api.renderHTML(published);
  assert.match(publishedHtml,/Fencing: 3 jobs won for \$11,037/);
  assert.match(publishedHtml,/against \$171k quoted; 5 lost; 0 of 12 tracked quotes accepted online/);
  assert.doesNotMatch(publishedHtml,/; – lost; – of – tracked/);
  published.rows[0].metrics.prior={...published.rows[0].metrics.prior,quoted_jobs:12,quoted_value:100000,won:1};
  const labelled=api.model(published);
  assert.equal(labelled.previous('quoted_jobs',labelled.quotedLane),12);
  assert.equal(labelled.previous('quoted_value',labelled.quotedValueLane),100000);
  assert.equal(labelled.previous('won',labelled.winLane),1);
  assert.equal(labelled.previous('quoted_jobs'),null);
  const labelledHtml=api.renderHTML(published);
  assert.match(labelledHtml,/up 6 on last week \(12\)/);
  assert.match(labelledHtml,/up \$70,908 on last week \(\$100,000\)/);
  assert.match(labelledHtml,/up 2 on last week \(1\)/);
  const both=fresh();
  both.rows[0].metrics.prior={...both.rows[0].metrics.prior,quoted_jobs:12,quoted_value:100000,won:1};
  both.rows[1].coverage.gaps=both.rows[1].coverage.gaps.filter(g=>g!=='patio_quote_total'&&g!=='patio_wins');
  both.rows[1].metrics.quoted_jobs=4;
  both.rows[1].metrics.quoted_value=22000;
  both.rows[1].metrics.quote_rows=[{job:'SWP-1',value:22000,source:'Web'}];
  both.rows[1].metrics.wins=[{job:'SWP-1',value:22000,proof:'staff stamp',rep:'Nithin',source:'Web'}];
  const combined=api.model(both);
  assert.equal(combined.quotedLane,null);
  assert.equal(combined.winLane,null);
  assert.equal(combined.previous('quoted_jobs',combined.quotedLane),null);
  assert.equal(combined.previous('won',combined.winLane),null);
  assert.equal(combined.scalar('lost_week',combined.winLane),null);
  const combinedHtml=api.renderHTML(both);
  assert.match(combinedHtml,/4 jobs won for \$33,037/);
  assert.match(combinedHtml,/against \$193k quoted; – lost; – of – tracked/);
  assert.doesNotMatch(combinedHtml,/up 6 on last week \(12\)/);
  both.rows[1].metrics.prior={quoted_jobs:5,quoted_value:20000,won:2};
  const filled=api.model(both);
  assert.equal(filled.previous('quoted_jobs',filled.quotedLane),17);
  assert.equal(filled.previous('quoted_value',filled.quotedValueLane),120000);
  assert.equal(filled.previous('won',filled.winLane),3);
  assert.match(api.renderHTML(both),/up 5 on last week \(17\)/);
  assert.match(api.renderHTML(both),/up 1 on last week \(3\)/);
  const missing=fresh();
  missing.rows.pop();
  const missingHtml=api.renderHTML(missing);
  assert.match(missingHtml,/Patio has no report for this week\. Showing fencing quotes and wins\./);
  assert.doesNotMatch(missingHtml,/Combined measures stay unavailable/);
  missing.rows[0].coverage.gaps.push('quoted_jobs','quoted_value','quote_rows','wins');
  assert.match(api.renderHTML(missing),/Patio has no report for this week\. Combined measures stay unavailable\./);
});

test('All story names mixed quote and win covers on their own phrases',()=>{
  const published=fresh();
  const publishedModel=api.model(published);
  assert.equal(publishedModel.storyLane,'fencing');
  assert.equal(publishedModel.winLane,'fencing');
  assert.equal(publishedModel.quotedLane,'fencing');
  const publishedHtml=api.renderHTML(published);
  assert.match(publishedHtml,/Fencing: 3 jobs won for \$11,037/);
  assert.match(publishedHtml,/against \$171k quoted; 5 lost; 0 of 12 tracked quotes accepted online/);
  assert.match(publishedHtml,/Patio quotes and wins: –\./);
  assert.doesNotMatch(publishedHtml,/\$11,037 \(fencing\)|quoted \(fencing\)/);
  const patioQuotes=fresh();
  patioQuotes.rows[1].coverage.gaps=patioQuotes.rows[1].coverage.gaps.filter(g=>g!=='patio_quote_total');
  patioQuotes.rows[1].metrics.quoted_jobs=4;
  patioQuotes.rows[1].metrics.quoted_value=22000;
  patioQuotes.rows[1].metrics.quote_rows=[{job:'SWP-1',value:22000,source:'Web'}];
  const quotesOnly=api.model(patioQuotes);
  assert.equal(quotesOnly.quotedJobs,22);
  assert.equal(quotesOnly.quotedValue,192907.55);
  assert.equal(quotesOnly.winCount,3);
  assert.equal(quotesOnly.quotedLane,null);
  assert.equal(quotesOnly.quotedValueLane,null);
  assert.equal(quotesOnly.winLane,'fencing');
  assert.equal(quotesOnly.storyLane,null);
  assert.equal(quotesOnly.scalar('lost_week',quotesOnly.storyLane),null);
  const quotesHtml=api.renderHTML(patioQuotes);
  assert.match(quotesHtml,/3 jobs won for \$11,037 \(fencing\)/);
  assert.match(quotesHtml,/against \$193k quoted; – lost; – of – tracked quotes accepted online/);
  assert.doesNotMatch(quotesHtml,/Fencing: 3 jobs won|Patio quotes and wins/);
  assert.doesNotMatch(quotesHtml,/Quotes sent \(fencing\)|Quoted value \(fencing\)/);
  assert.match(quotesHtml,/Won \(fencing\)/);
  const patioWins=fresh();
  patioWins.rows[1].coverage.gaps=patioWins.rows[1].coverage.gaps.filter(g=>g!=='patio_wins');
  patioWins.rows[1].metrics.wins=[{job:'SWP-1',value:22000,proof:'staff stamp',rep:'Nithin',source:'Web'}];
  const winsOnly=api.model(patioWins);
  assert.equal(winsOnly.quotedJobs,18);
  assert.equal(winsOnly.quotedValue,170907.55);
  assert.equal(winsOnly.winCount,4);
  assert.equal(winsOnly.quotedLane,'fencing');
  assert.equal(winsOnly.quotedValueLane,'fencing');
  assert.equal(winsOnly.winLane,null);
  assert.equal(winsOnly.storyLane,null);
  assert.equal(winsOnly.scalar('lost_week',winsOnly.storyLane),null);
  const winsHtml=api.renderHTML(patioWins);
  assert.match(winsHtml,/4 jobs won for \$33,037/);
  assert.match(winsHtml,/against \$171k quoted \(fencing\); – lost; – of – tracked quotes accepted online/);
  assert.doesNotMatch(winsHtml,/Fencing: 4 jobs won|Patio quotes and wins|\$33,037 \(fencing\)/);
  assert.match(winsHtml,/Quotes sent \(fencing\)/);
  assert.match(winsHtml,/Quoted value \(fencing\)/);
  assert.doesNotMatch(winsHtml,/Won \(fencing\)/);
});

test('per-rep table uses three Khairo wins and withholds unnamed quotes',()=>{const d=fresh(),all=api.model(d),fencing=api.model(d,{lane:'fencing'}),patio=api.model(d,{lane:'patio'}),stratco=api.model(d,{lane:'fencing',source:'Stratco'});const khairo=all.reps.find(r=>r.name==='Khairo'),nithin=all.reps.find(r=>r.name==='Nithin'),marnin=all.reps.find(r=>r.name==='Marnin');assert.deepEqual(all.reps.map(r=>r.name),['Khairo','Nithin','Marnin']);assert.equal(khairo.won,3);assert.equal(khairo.wonValue,11037.4);assert.deepEqual(all.wins.filter(w=>w.rep==='Khairo').map(w=>w.job).sort(),['SWF-261383','SWF-261397','SWF-261413']);assert.equal(khairo.waiting,18);assert.equal(khairo.overWeek,2);assert.equal(nithin.waiting,10);assert.equal(nithin.won,0);assert.equal(marnin.waiting,2);assert.equal(khairo.quotes,null);assert.equal(nithin.quotedValue,null);assert.equal(fencing.reps.find(r=>r.name==='Khairo').won,3);assert.equal(fencing.reps.find(r=>r.name==='Nithin').waiting,0);assert.equal(patio.reps.find(r=>r.name==='Khairo').won,null);assert.equal(patio.reps.find(r=>r.name==='Nithin').waiting,10);assert.equal(stratco.reps.find(r=>r.name==='Khairo').won,0);assert.equal(stratco.reps.find(r=>r.name==='Khairo').waiting,5);const html=api.renderHTML(d),block=html.slice(html.indexOf('class="card reps"'),html.indexOf('class="grid"'));assert.match(block,/Khairo/);assert.match(block,/not in store yet/);assert.doesNotMatch(block,/fill|bar-space|general-bar/);d.rows[0].metrics.quote_rows[0].rep='Khairo';const named=api.model(d,{lane:'fencing'});assert.equal(named.reps.find(r=>r.name==='Khairo').quotes,1);assert.equal(named.reps.find(r=>r.name==='Khairo').quotedValue,36685);assert.equal(named.reps.find(r=>r.name==='Nithin').quotes,0);assert.doesNotMatch(api.renderHTML(d,{lane:'fencing'}).slice(0,api.renderHTML(d,{lane:'fencing'}).indexOf('class="grid"')),/not in store yet/);});
