const { test } = require('node:test');
const assert = require('node:assert/strict');
const { create, filteredJobs, week } = require('../../modules/ops-dispatch-core.js');
const deferred = () => { let resolve, reject; const promise = new Promise((a,b) => { resolve=a; reject=b; }); return {promise,resolve,reject}; };
const record = (id, version=0) => ({job:{id},version,source_version:'src1',groups:[],requirements:[],drafts:[]});
function harness(get, post) { let id=0; return create({get,post,id:()=>`request-${++id}`}); }
test('population consumes every cursor, retains unresolved/no-PO work and filters only presentation',async()=>{
 const pages=[]; const core=harness(async(action,p)=>{if(action==='dispatch_job')return record(p.job_id);pages.push(p.cursor);return p.cursor?{jobs:[{id:'b',work_type:'patio',eligibility:{state:'unresolved'}}],next_cursor:null,coverage:{complete:true}}:{jobs:[{id:'a',work_type:'fencing'}],next_cursor:'second',coverage:{complete:false}};});
 await core.list();assert.deepEqual(pages,[undefined,'second']);assert.equal(core.state.jobs.length,2);assert.equal(core.state.coverage.complete,true);assert.equal(filteredJobs(core.state.jobs,{trade:'patio'})[0].id,'b');assert.equal(core.state.jobs.length,2);
});
test('failed later page retains captured jobs with incomplete coverage',async()=>{const core=harness(async(action,p)=>{if(action==='dispatch_job')return record(p.job_id);if(p.cursor)throw Error('read failed');return{jobs:[{id:'a'}],next_cursor:'more',coverage:{complete:false}};});await core.list();assert.equal(core.state.jobs.length,1);assert.equal(core.state.coverage.complete,false);assert.match(core.state.error,/read failed/);});
test('repeated cursor refuses complete population claim',async()=>{const core=harness(async(action,p)=>action==='dispatch_job'?record(p.job_id):{jobs:[{id:'a'}],next_cursor:'repeat',coverage:{complete:false}});await core.list();assert.match(core.state.error,/Repeated/);});
test('rapid job selection preserves each job editor and ignores older same-job read',async()=>{const first=deferred(),second=deferred();let reads=0;const core=harness(async(_,p)=>p.job_id==='a'?(++reads===1?first.promise:second.promise):record('b'));const a=core.select('a');core.edit('a','draft:d',{body:'human work'});await core.select('b');const a2=core.load('a');second.resolve(record('a',2));await a2;first.resolve(record('a',1));await a;assert.equal(core.state.selectedId,'b');assert.equal(core.state.records.get('a').version,2);assert.equal(core.editor('a','draft:d').body,'human work');});
test('unknown write retry preserves exact idempotency and reply identity',async()=>{let calls=[];const core=harness(async(_,p)=>record(p.job_id),async(_,payload)=>{calls.push(payload);if(calls.length===1)throw Error('network uncertain');return record('a',1);});await core.select('a');const draft={id:'d',thread_id:'original-thread',po_id:'p',sender:'ops@example.com',to:['supplier@example.com'],cc:[],subject:'exact',body:'human content',attachments:[{id:'f',revision:'r1',source_ref:'source'}]};await assert.rejects(core.command('a','draft_upsert',draft));await assert.rejects(core.command('a','draft_upsert',draft),/Resolve/);await core.retry('a');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[1].payload.thread_id,'original-thread');assert.equal(core.state.records.get('a').version,1);});
test('conflicting write requires fresh read, keeps unsaved buffer, cannot retry stale command',async()=>{let version=0;const core=harness(async(_,p)=>record(p.job_id,version),async()=>{version=1;throw Object.assign(Error('changed sources'),{status:409});});await core.select('a');core.edit('a','note',{text:'keep me'});await assert.rejects(core.command('a','note_upsert',{id:'n',text:'keep me'}));await assert.rejects(core.retry('a'),/Reload/);await core.resolveConflict('a');assert.equal(core.state.records.get('a').version,1);assert.equal(core.editor('a','note').text,'keep me');assert.equal(core.state.pending.size,0);});
test('saving old editor value never clears typing made during pending write',async()=>{const core=harness(async(_,p)=>record(p.job_id));core.edit('a','draft:d',{body:'before'});const saved=core.editor('a','draft:d');core.edit('a','draft:d',{body:'after'});core.clearEditor('a','draft:d',saved);assert.equal(core.editor('a','draft:d').body,'after');});
test('calendar layer choices share the same source IDs, failed read retains stale evidence as partial',async()=>{let fail=false;const core=harness(async()=>{if(fail)throw Error('calendar offline');return {events:[{id:'po:real',job_id:'a',layer:'materials'}],undated:[],coverage:{complete:true}};});await core.calendar('2026-09-14','2026-09-20');core.setLayer('materials',false);assert.equal(core.state.calendar.events[0].id,'po:real');assert.equal(core.state.layers.materials,false);fail=true;await core.calendar('2026-09-14','2026-09-20');assert.equal(core.state.calendar.coverage.complete,false);assert.match(core.state.calendar.error,/offline/);});
test('Perth week is stable across UTC midnight boundary',()=>assert.deepEqual(week(new Date('2026-09-13T17:00:00Z')),['2026-09-14','2026-09-15','2026-09-16','2026-09-17','2026-09-18','2026-09-19','2026-09-20']));

test('definite validation refusal allows corrected retained work without replaying invalid command',async()=>{let count=0;const core=harness(async(_,p)=>record(p.job_id),async()=>{if(++count===1)throw Object.assign(Error('Quantity required'),{status:400});return record('a',1);});await core.select('a');core.edit('a','requirement',{description:'keep'});await assert.rejects(core.command('a','requirement_review',{id:'r'}));assert.equal(core.state.pending.size,0);await core.command('a','requirement_upsert',{id:'r',quantity:2});assert.equal(core.state.records.get('a').version,1);assert.equal(core.editor('a','requirement').description,'keep');});
test('shared stock and cross-job supply consume every page without losing either kind',async()=>{const core=harness(async(_,p)=>({supply_lots:[{id:p.kind+':'+(p.cursor||'first'),quantity:4,unit:'each'}],next_cursor:p.cursor?null:'second',coverage:{complete:!!p.cursor}}));await Promise.all([core.supply('po'),core.supply('stock')]);assert.equal(core.state.supply.lots.length,4);assert.deepEqual(core.state.supply.coverage,{po:true,stock:true});});
test('reading held execution capabilities never posts or contacts execution',async()=>{let posts=0;const core=harness(async()=>({actions:[],capabilities:{release_hold:true,approval_enabled:false}}),async()=>{posts++;});await core.execution('a');assert.equal(core.state.executions.get('a').capabilities.release_hold,true);assert.equal(posts,0);});
