const { test } = require('node:test');
const assert = require('node:assert/strict');
const { create, filteredJobs, week } = require('../../modules/ops-dispatch-core.js');
const deferred = () => { let resolve, reject; const promise = new Promise((a,b) => { resolve=a; reject=b; }); return {promise,resolve,reject}; };
const record = (id, version=0) => ({job:{id},version,source_version:'src1',groups:[],requirements:[],drafts:[]});
function harness(get, post) { let id=0; return create({get,post,id:()=>`request-${++id}`}); }
test('population consumes every cursor, retains unresolved/no-PO work and filters only presentation',async()=>{
 const pages=[]; const core=harness(async(action,p)=>{if(action==='dispatch_job')return record(p.job_id);pages.push(p.cursor);return p.cursor?{jobs:[{id:'b',work_type:'patio',eligibility:{state:'unresolved'}}],next_cursor:null,coverage:{complete:true}}:{jobs:[{id:'a',work_type:'fencing'}],next_cursor:'second',coverage:{complete:false}};});
 await core.list();assert.deepEqual(pages,[undefined,'second']);assert.equal(core.state.jobs.length,2);assert.equal(core.state.coverage.complete,true);assert.equal(filteredJobs(core.state.jobs,{trade:'patio'})[0].id,'b');assert.equal(core.state.jobs.length,2);
});
test('trade filter matches the normalized returned work type exactly',()=>{const jobs=[{id:'a',work_type:'patio'},{id:'b',work_type:'patio repair'},{id:'c',work_type:'  Patio  ',next_action:'order'}];assert.deepEqual(filteredJobs(jobs,{trade:'patio'}).map(job=>job.id),['a','c']);assert.deepEqual(filteredJobs(jobs,{trade:'patio',workflow:'order'}).map(job=>job.id),['c']);});
test('failed later page retains captured jobs with incomplete coverage',async()=>{const core=harness(async(action,p)=>{if(action==='dispatch_job')return record(p.job_id);if(p.cursor)throw Error('read failed');return{jobs:[{id:'a'}],next_cursor:'more',coverage:{complete:false}};});await core.list();assert.equal(core.state.jobs.length,1);assert.equal(core.state.coverage.complete,false);assert.match(core.state.error,/read failed/);});
test('repeated cursor refuses complete population claim',async()=>{const core=harness(async(action,p)=>action==='dispatch_job'?record(p.job_id):{jobs:[{id:'a'}],next_cursor:'repeat',coverage:{complete:false}});await core.list();assert.match(core.state.error,/Repeated/);});
test('rapid job selection preserves each job editor and coalesces pending same-job reads',async()=>{const first=deferred();let reads=0;const core=harness(async(_,p)=>{reads++;return p.job_id==='a'?first.promise:record('b');});const a=core.select('a');core.edit('a','draft:d',{body:'human work'});await core.select('b');const a2=core.select('a');assert.equal(reads,2);first.resolve(record('a',1));await a;await a2;assert.equal(core.state.selectedId,'a');assert.equal(core.state.records.get('a').version,1);assert.equal(core.editor('a','draft:d').body,'human work');});
test('same-job reads coalesce and expose verification evidence',async()=>{const first=deferred();let reads=0;const core=harness(async(_,p)=>{reads++;return p.job_id==='a'?first.promise:record(p.job_id);});const a=core.load('a'),b=core.load('a');assert.equal(reads,1);assert.equal(core.state.evidence.get('a').loading,true);first.resolve(record('a',1));assert.equal(await a,await b);assert.equal(core.state.evidence.get('a').loading,false);assert.equal(core.state.evidence.get('a').verified,true);assert.equal(core.state.evidence.get('a').error,null);assert.equal(typeof core.state.evidence.get('a').lastSuccessAt,'number');});
test('failed selected job read revokes current verification until authoritative success',async()=>{let fail=false;const core=harness(async(_,p)=>{if(fail)throw Error('read failed');return record(p.job_id,1);});await core.load('a');const lastSuccessAt=core.state.evidence.get('a').lastSuccessAt;fail=true;await assert.rejects(core.load('a'),/read failed/);assert.equal(core.state.evidence.get('a').verified,false);assert.equal(core.state.evidence.get('a').error,'read failed');assert.equal(core.state.evidence.get('a').lastSuccessAt,lastSuccessAt);await assert.rejects(core.command('a','note_upsert',{id:'n'}),/Refresh this job/);fail=false;await core.load('a');assert.equal(core.state.evidence.get('a').verified,true);assert.equal(core.state.evidence.get('a').error,null);});
test('older selected job read cannot replace newer command result or verify stale snapshot',async()=>{const stale=deferred();let reads=0;const core=harness(async(_,p)=>{reads++;return reads===1?record(p.job_id,0):stale.promise;},async()=>record('a',2));await core.load('a');const old=core.load('a');await new Promise(resolve=>setImmediate(resolve));await core.command('a','note_upsert',{id:'n'});stale.resolve(record('a',1));await old;assert.equal(core.state.records.get('a').version,2);assert.equal(core.state.evidence.get('a').verified,true);});
test('lower-version authoritative read cannot verify freshness',async()=>{let version=2;const core=harness(async(_,p)=>record(p.job_id,version));await core.load('a');version=1;await core.load('a');assert.equal(core.state.records.get('a').version,2);assert.equal(core.state.evidence.get('a').verified,false);assert.match(core.state.evidence.get('a').error,/Stale Dispatch response/);});
test('unknown write retry preserves exact idempotency and reply identity',async()=>{let calls=[];const core=harness(async(_,p)=>record(p.job_id),async(_,payload)=>{calls.push(payload);if(calls.length===1)throw Error('network uncertain');return record('a',1);});await core.select('a');const draft={id:'d',thread_id:'original-thread',po_id:'p',sender:'ops@example.com',to:['supplier@example.com'],cc:[],subject:'exact',body:'human content',attachments:[{id:'f',revision:'r1',source_ref:'source'}]};await assert.rejects(core.command('a','draft_upsert',draft));await assert.rejects(core.command('a','draft_upsert',draft),/Resolve/);await core.retry('a');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[1].payload.thread_id,'original-thread');assert.equal(core.state.records.get('a').version,1);});
test('conflicting write requires fresh read, keeps unsaved buffer, cannot retry stale command',async()=>{let version=0;const core=harness(async(_,p)=>record(p.job_id,version),async()=>{version=1;throw Object.assign(Error('changed sources'),{status:409});});await core.select('a');core.edit('a','note',{text:'keep me'});await assert.rejects(core.command('a','note_upsert',{id:'n',text:'keep me'}));await assert.rejects(core.retry('a'),/Reload/);await core.resolveConflict('a');assert.equal(core.state.records.get('a').version,1);assert.equal(core.editor('a','note').text,'keep me');assert.equal(core.state.pending.size,0);});
test('saving old editor value never clears typing made during pending write',async()=>{const core=harness(async(_,p)=>record(p.job_id));core.edit('a','draft:d',{body:'before'});const saved=core.editor('a','draft:d');core.edit('a','draft:d',{body:'after'});core.clearEditor('a','draft:d',saved);assert.equal(core.editor('a','draft:d').body,'after');});
test('calendar layer choices share the same source IDs, failed read retains stale evidence as partial',async()=>{let fail=false;const core=harness(async()=>{if(fail)throw Error('calendar offline');return {events:[{id:'po:real',job_id:'a',layer:'materials'}],undated:[],coverage:{complete:true}};});await core.calendar('2026-09-14','2026-09-20');core.setLayer('materials',false);assert.equal(core.state.calendar.events[0].id,'po:real');assert.equal(core.state.calendar.loadedRange.from,'2026-09-14');assert.equal(core.state.layers.materials,false);fail=true;await core.calendar('2026-09-21','2026-09-27');assert.equal(core.state.calendar.loadedRange.from,'2026-09-14');assert.equal(core.state.calendar.coverage.complete,false);assert.match(core.state.calendar.error,/offline/);});
test('older calendar range cannot overwrite newer loaded range',async()=>{const slow=deferred();let reads=0;const core=harness(async()=>{reads++;return reads===1?slow.promise:{events:[{id:'new'}],undated:[],coverage:{complete:true}};});const old=core.calendar('2026-09-14','2026-09-20');await core.calendar('2026-09-21','2026-09-27');assert.equal(core.state.calendar.loadedRange.from,'2026-09-21');slow.resolve({events:[{id:'old'}],undated:[],coverage:{complete:true}});await old;assert.equal(core.state.calendar.loadedRange.from,'2026-09-21');assert.equal(core.state.calendar.events[0].id,'new');});
test('Perth week is stable across UTC midnight boundary',()=>assert.deepEqual(week(new Date('2026-09-13T17:00:00Z')),['2026-09-14','2026-09-15','2026-09-16','2026-09-17','2026-09-18','2026-09-19','2026-09-20']));

test('definite validation refusal allows corrected retained work without replaying invalid command',async()=>{let count=0;const core=harness(async(_,p)=>record(p.job_id),async()=>{if(++count===1)throw Object.assign(Error('Quantity required'),{status:400});return record('a',1);});await core.select('a');core.edit('a','requirement',{description:'keep'});await assert.rejects(core.command('a','requirement_review',{id:'r'}));assert.equal(core.state.pending.size,0);await core.command('a','requirement_upsert',{id:'r',quantity:2});assert.equal(core.state.records.get('a').version,1);assert.equal(core.editor('a','requirement').description,'keep');});
test('shared stock and cross-job supply consume every page without losing either kind',async()=>{const core=harness(async(_,p)=>({supply_lots:[{id:p.kind+':'+(p.cursor||'first'),quantity:4,unit:'each'}],next_cursor:p.cursor?null:'second',coverage:{complete:!!p.cursor}}));await Promise.all([core.supply('po'),core.supply('stock')]);assert.equal(core.state.supply.lots.length,4);assert.deepEqual(core.state.supply.coverage,{po:true,stock:true});});
test('reading held execution capabilities never posts or contacts execution',async()=>{let posts=0;const core=harness(async()=>({actions:[],capabilities:{release_hold:true,approval_enabled:false}}),async()=>{posts++;});await core.execution('a');assert.equal(core.state.executions.get('a').capabilities.release_hold,true);assert.equal(posts,0);});
test('successful execution status read notifies subscribers',async()=>{let seen=0;const core=harness(async()=>({actions:[{status:'held'}],coverage:{complete:true},capabilities:{release_hold:true}}));core.subscribe(state=>{if(state.executions.get('a')?.actions?.[0]?.status==='held')seen++;});await core.execution('a');assert.equal(seen,1);});

test('uncertain execution keeps a local recovery hold and cannot blindly repost',async()=>{let posts=0;const core=harness(async()=>({actions:[],coverage:{complete:true},capabilities:{release_hold:false}}),async()=>{posts++;throw Error('network uncertainty');});await assert.rejects(core.executeDraft('a','d','approval'));assert.equal(core.state.executions.get('a').uncertain,true);await assert.rejects(core.executeDraft('a','d','approval'),/Read back/);assert.equal(posts,1);});
test('status refresh during pending execution keeps duplicate-send guard',async()=>{const send=deferred();let executePosts=0;const core=harness(async(action)=>action==='dispatch_execution'?{actions:[],coverage:{complete:true},capabilities:{release_hold:false}}:record('a'),async(action)=>{if(action==='dispatch_execute'){executePosts++;await send.promise;return {accepted:true};}});const executing=core.executeDraft('a','d','approval');assert.equal(core.state.executions.get('a').submitting,true);await core.execution('a');assert.equal(core.state.executions.get('a').submitting,true);await assert.rejects(core.executeDraft('a','d','approval'),/Read back/);assert.equal(executePosts,1);send.resolve();await executing;assert.equal(core.state.executions.get('a').submitting,false);});
test('failed status refresh during pending execution keeps duplicate-send guard',async()=>{const send=deferred();let executePosts=0;const core=harness(async(action)=>{if(action==='dispatch_execution')throw Error('status offline');return record('a');},async(action)=>{if(action==='dispatch_execute'){executePosts++;await send.promise;return {accepted:true};}});const executing=core.executeDraft('a','d','approval');await core.execution('a');assert.equal(core.state.executions.get('a').submitting,true);assert.match(core.state.executions.get('a').error,/status offline/);await assert.rejects(core.executeDraft('a','d','approval'),/Read back/);assert.equal(executePosts,1);send.resolve();await executing;assert.equal(core.state.executions.get('a').submitting,false);});
test('older execution status read cannot replace newer readback state',async()=>{const slow=deferred();let reads=0;const core=harness(async(action)=>{if(action==='dispatch_execution'){reads++;return reads===1?slow.promise:{actions:[{status:'outcome_unknown',approval_id:'approval'}],coverage:{complete:true},capabilities:{release_hold:false}};}return record('a');},async()=>({accepted:true}));const stale=core.execution('a');await core.execution('a');assert.equal(core.state.executions.get('a').actions[0].status,'outcome_unknown');slow.resolve({actions:[{status:'held'}],coverage:{complete:true},capabilities:{release_hold:false}});await stale;assert.equal(core.state.executions.get('a').actions[0].status,'outcome_unknown');});
test('readback keeps uncertain execution held without a safe-retry proof',async()=>{let executePosts=0,readbacks=0;const core=harness(async(action)=>action==='dispatch_execution'?{actions:[{status:'accepted_not_delivered',approval_id:'approval'}],coverage:{complete:true},capabilities:{release_hold:false}}:record('a'),async(action)=>{if(action==='dispatch_execute'){executePosts++;throw Error('network uncertainty');}if(action==='dispatch_execution_readback'){readbacks++;return {receipt:{provider:'checked'}};}});await assert.rejects(core.executeDraft('a','d','approval'));assert.equal(core.state.executions.get('a').uncertain,true);await core.execution('a');assert.equal(core.state.executions.get('a').uncertain,true);await core.readbackExecution('a','approval');assert.equal(readbacks,1);assert.equal(core.state.executions.get('a').uncertain,true);await assert.rejects(core.executeDraft('a','d','approval'),/Read back/);assert.equal(executePosts,1);});
test('matching readback clears only the proven accepted approval',async()=>{let readback=false;const core=harness(async(action)=>{if(action==='dispatch_execution')return readback?{actions:[{id:'action-1',status:'accepted_not_delivered',approval_id:'approval-1'},{id:'action-2',status:'outcome_unknown',approval_id:'approval-2'}],coverage:{complete:true},capabilities:{release_hold:false}}:{actions:[{id:'action-2',status:'outcome_unknown',approval_id:'approval-2'}],coverage:{complete:true},capabilities:{release_hold:false}};return record('a');},async(action)=>{if(action==='dispatch_execute')throw Error('network uncertainty');if(action==='dispatch_execution_readback'){readback=true;return {action:{id:'action-1',status:'accepted_not_delivered',approval_id:'approval-1'},retry_safe:false,readback_required:false,readback_recorded:true};}});await assert.rejects(core.executeDraft('a','d','approval-1'));assert.deepEqual(core.state.executions.get('a').uncertainApprovals.sort(),['approval-1','approval-2']);await core.readbackExecution('a','approval-1');assert.equal(core.state.executions.get('a').uncertain,true);assert.deepEqual(core.state.executions.get('a').uncertainApprovals,['approval-2']);assert.equal(core.state.executions.get('a').completedApprovals.includes('approval-1'),true);});
test('mismatched readback action stays uncertain',async()=>{let readback=false;const core=harness(async(action)=>{if(action==='dispatch_execution')return readback?{actions:[{id:'fresh-action',status:'accepted_not_delivered',approval_id:'approval'}],coverage:{complete:true},capabilities:{release_hold:false}}:{actions:[],coverage:{complete:true},capabilities:{release_hold:false}};return record('a');},async(action)=>{if(action==='dispatch_execute')throw Error('network uncertainty');if(action==='dispatch_execution_readback'){readback=true;return {action:{id:'other-action',status:'accepted_not_delivered',approval_id:'approval'},retry_safe:false,readback_required:false,readback_recorded:true};}});await assert.rejects(core.executeDraft('a','d','approval'));await core.readbackExecution('a','approval');assert.equal(core.state.executions.get('a').uncertain,true);assert.equal(core.state.executions.get('a').completedApprovals.includes('approval'),false);});
test('readback requiring another check stays uncertain',async()=>{let readback=false;const core=harness(async(action)=>{if(action==='dispatch_execution')return readback?{actions:[{id:'action',status:'accepted_not_delivered',approval_id:'approval'}],coverage:{complete:true},capabilities:{release_hold:false}}:{actions:[],coverage:{complete:true},capabilities:{release_hold:false}};return record('a');},async(action)=>{if(action==='dispatch_execute')throw Error('network uncertainty');if(action==='dispatch_execution_readback'){readback=true;return {action:{id:'action',status:'accepted_not_delivered',approval_id:'approval'},retry_safe:false,readback_required:true,readback_recorded:true};}});await assert.rejects(core.executeDraft('a','d','approval'));await core.readbackExecution('a','approval');assert.equal(core.state.executions.get('a').uncertain,true);assert.equal(core.state.executions.get('a').completedApprovals.includes('approval'),false);});
test('stale readback status cannot clear a newer unknown action',async()=>{const slow=deferred();let mode='initial';const core=harness(async(action)=>{if(action==='dispatch_execution'){if(mode==='readback')return slow.promise;if(mode==='newer')return {actions:[{id:'action-2',status:'outcome_unknown',approval_id:'approval-2'}],coverage:{complete:true},capabilities:{release_hold:false}};return {actions:[],coverage:{complete:true},capabilities:{release_hold:false}};}return record('a');},async(action)=>{if(action==='dispatch_execute')throw Error('network uncertainty');if(action==='dispatch_execution_readback'){mode='readback';return {action:{id:'action-1',status:'accepted_not_delivered',approval_id:'approval-1'},retry_safe:false,readback_required:false,readback_recorded:true};}});await assert.rejects(core.executeDraft('a','d','approval-1'));const readback=core.readbackExecution('a','approval-1');await new Promise(resolve=>setImmediate(resolve));mode='newer';await core.execution('a');slow.resolve({actions:[{id:'action-1',status:'accepted_not_delivered',approval_id:'approval-1'}],coverage:{complete:true},capabilities:{release_hold:false}});await readback;assert.equal(core.state.executions.get('a').uncertain,true);assert.deepEqual(core.state.executions.get('a').uncertainApprovals.sort(),['approval-1','approval-2']);assert.equal(core.state.executions.get('a').completedApprovals.includes('approval-1'),false);});
test('completed approval cannot be resent when later status omits the action',async()=>{const core=harness(async(action)=>action==='dispatch_execution'?{actions:[],coverage:{complete:true},capabilities:{release_hold:false}}:record('a'),async()=>({accepted:true}));await core.executeDraft('a','d','approval');await core.execution('a');assert.equal(core.state.executions.get('a').completedApprovals.includes('approval'),true);await assert.rejects(core.executeDraft('a','d','approval'),/already has an execution receipt/);});
test('readback does not clear a pending execution guard',async()=>{const send=deferred();let readback=false;const core=harness(async(action)=>action==='dispatch_execution'?{actions:readback?[{id:'action',status:'accepted_not_delivered',approval_id:'approval'}]:[],coverage:{complete:true},capabilities:{release_hold:false}}:record('a'),async(action)=>{if(action==='dispatch_execute'){await send.promise;return {accepted:true};}if(action==='dispatch_execution_readback'){readback=true;return {action:{id:'action',status:'accepted_not_delivered',approval_id:'approval'},retry_safe:false,readback_required:false,readback_recorded:true};}});const executing=core.executeDraft('a','d','approval');await new Promise(resolve=>setImmediate(resolve));await core.readbackExecution('a','approval');assert.equal(core.state.executions.get('a').submitting,true);send.resolve();await executing;assert.equal(core.state.executions.get('a').submitting,false);});
test('completed execute clears submitting when its status read is superseded',async()=>{const slow=deferred();let reads=0;const core=harness(async(action)=>{if(action==='dispatch_execution'){reads++;return reads===1?slow.promise:{actions:[{status:'outcome_unknown',approval_id:'approval'}],coverage:{complete:true},capabilities:{release_hold:false}};}return record('a');},async()=>({accepted:true}));const executing=core.executeDraft('a','d','approval');await new Promise(resolve=>setImmediate(resolve));await core.execution('a');assert.equal(core.state.executions.get('a').submitting,true);slow.resolve({actions:[{status:'held'}],coverage:{complete:true},capabilities:{release_hold:false}});await executing;assert.equal(core.state.executions.get('a').submitting,false);assert.equal(core.state.executions.get('a').actions[0].status,'outcome_unknown');});
test('successful execute with failed status read remains held uncertain',async()=>{const core=harness(async(action)=>{if(action==='dispatch_execution')throw Error('status offline');return record('a');},async()=>({accepted:true}));await core.executeDraft('a','d','approval');assert.equal(core.state.executions.get('a').submitting,false);assert.equal(core.state.executions.get('a').uncertain,true);assert.equal(core.state.executions.get('a').coverage.complete,false);assert.equal(core.state.executions.get('a').capabilities.release_hold,true);});
test('server-reported unknown outcome remains guarded even if later status is empty',async()=>{
 let unknown=true,posts=0;
 const core=harness(async()=>({actions:unknown?[{status:'outcome_unknown',approval_id:'approval'}]:[],coverage:{complete:true},capabilities:{release_hold:false}}),async()=>{posts++;return {accepted:true};});
 await core.executeDraft('a','d','approval');
 assert.equal(core.state.executions.get('a').uncertain,true);
 unknown=false;await core.execution('a');
 await assert.rejects(core.executeDraft('a','d','approval'),/Read back/);
 assert.equal(posts,1);
});
test('failed status and readback preserve an uncertain send hold',async()=>{
 let offline=false,posts=0;
 const core=harness(async()=>{if(offline)throw Error('status offline');return {actions:[],coverage:{complete:true},capabilities:{release_hold:false}};},async()=>{posts++;throw Error('uncertain response');});
 await assert.rejects(core.executeDraft('a','d','approval'));
 offline=true;await core.execution('a');
 assert.equal(core.state.executions.get('a').uncertain,true);
 assert.equal(core.state.executions.get('a').coverage.complete,false);
 await assert.rejects(core.readbackExecution('a','approval'));
 await assert.rejects(core.executeDraft('a','d','approval'),/Read back/);
 assert.equal(posts,2);
});
